spring.application.name=MessagingSystem
# Application Name
server.port=8083
logging.level.org.springframework.security=DEBUG


# MongoDB Configuration
spring.data.mongodb.host=10.1.22.176
spring.data.mongodb.port=27017
spring.data.mongodb.database=messagingApp
# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# File Storage Path
#file.storage-path=C:\Users\abenezert\Desktop\Files for test
#file.storage-path=C:\\Users\\Abinet\\Desktop\\email
file.storage-patH=F:\\EmailZip
spring.jackson.serialization.write-dates-as-timestamps=false

# Security Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=2419200000 

# LDAP Configuration
ldap.username=CN=digildap,OU=ITS Users,OU=IT,DC=LIB5,DC=COM
ldap.password=D!g!ld4p
ldap.url=ldap://10.1.10.1:389
ldap.search-base=OU=LIB Users & Computers,DC=LIB5,DC=COM



